services:
  kd-frontend:
    container_name: kd-frontend
    restart: always
    network_mode: host
    build:
      context: ./kd-frontend
      dockerfile: ./kd-frontend/Dockerfile
    ports:
      - "4200:80"
  kd-backend:
    container_name: kd-backend
    restart: always
    network_mode: host
    build:
      context: ./kd-backend
      dockerfile: ./kd-backend/Dockerfile
    ports:
      - "5018:8080"
      - "8081:8081"
